services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app  # Mount local backend folder to container
      - /usr/src/app/node_modules  # Prevent overwriting node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://database:27017/mydb
    depends_on:
      - database

  database:
    image: mongo
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app  # Ensure the local frontend code syncs with the container
      - /app/node_modules  # Prevent overwriting node_modules

volumes:
  mongodb_data:
